### ISSUE TITLE
Push to binstar difficulties

### ISSUE THREAD

**Issue by jchodera** [omnia-md/openmm-dev#1]
Jenkins ran into this error:

```
+ vagrant ssh --command 'binstar --quiet -t **** upload --force -u omnia miniconda/conda-bld/*/openmm-dev-*.tar.bz2'
Using binstar api site https://api.binstar.org
[warning] Distribution linux-64/openmm-dev-dev-py27_1.tar.bz2 already exists ... removing 
[warning] Distribution linux-64/openmm-dev-dev-py33_1.tar.bz2 already exists ... removing 
[ConnectionError] ('Connection aborted.', BadStatusLine("''",)) 
Traceback (most recent call last):
  File "/home/vagrant/miniconda/bin/binstar", line 6, in <module>
    sys.exit(main())
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 94, in main
    description=__doc__, version=version)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 76, in binstar_main
    return args.main(args)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/binstar_client/commands/upload.py", line 204, in main
    callback=upload_print_callback(args))
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/binstar_client/__init__.py", line 423, in upload
    s3res = requests.post(s3url, data=data_stream, verify=self.session.verify, timeout=10 * 60 * 60, headers=headers)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/requests/api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

**Comment by jchodera** [comment]
Seems to have been a fluke.
