### ISSUE TITLE
OSX package no longer uploading to binstar correctly

### ISSUE THREAD

**Issue by jchodera** [omnia-md/openmm-dev#4]
I get this weird error when [Jenkins tries to upload the `osx` package](https://jenkins.choderalab.org/job/conda-openmm-dev-osx-2/30/console):

```
+ binstar --quiet -t **** upload --force -u omnia --channel main miniconda/conda-bld/osx-64/openmm-dev-dev-py27_1.tar.bz2
Using binstar api site https://api.anaconda.org
[BinstarError] Invalid dist_id 
Traceback (most recent call last):
  File "/Users/jenkins-slave/workspace/conda-openmm-dev-osx-2/miniconda/bin/binstar", line 6, in <module>
    sys.exit(main())
  File "/Users/jenkins-slave/workspace/conda-openmm-dev-osx-2/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 94, in main
    description=__doc__, version=version)
  File "/Users/jenkins-slave/workspace/conda-openmm-dev-osx-2/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 76, in binstar_main
    return args.main(args)
  File "/Users/jenkins-slave/workspace/conda-openmm-dev-osx-2/miniconda/lib/python2.7/site-packages/binstar_client/commands/upload.py", line 204, in main
    callback=upload_print_callback(args))
  File "/Users/jenkins-slave/workspace/conda-openmm-dev-osx-2/miniconda/lib/python2.7/site-packages/binstar_client/__init__.py", line 435, in upload
    self._check_response(res)
  File "/Users/jenkins-slave/workspace/conda-openmm-dev-osx-2/miniconda/lib/python2.7/site-packages/binstar_client/__init__.py", line 160, in _check_response
    raise ErrCls(msg, res.status_code)
BinstarError: (u'Invalid dist_id', 400)
```

I wonder if deleting the binstar packages and trying again would work, but I am afraid this would wipe out our only `osx` packages.

@rmcgibbo or @kyleabeauchamp : Ever seen this before?

**Comment by rmcgibbo** [comment]
Not sure. I've never seen this before.

**Comment by jchodera** [comment]
I think it was just an issue related to the build number of the recipe having been bumped to 1 and there having been multiple packages with different build numbers uploaded.

I removed the old packages, reverted the build number to 0, and am rebuilding everything.  That seems to work.

Thanks!
