### ISSUE TITLE
binstar push difficulties

### ISSUE THREAD

**Issue by jchodera** [omnia-md/openmm-dev#5]
I seem to still be getting these errors when attempting to push from Jenkins to binstar:

```
+ vagrant ssh --command 'binstar --quiet -t **** upload --force -u omnia --channel main miniconda/conda-bld/*/openmm-dev-*.tar.bz2'
Using binstar api site https://api.anaconda.org
[warning] Distribution linux-64/openmm-dev-dev-py27_0.tar.bz2 already exists ... removing 
[BinstarError] Invalid dist_id 
Traceback (most recent call last):
  File "/home/vagrant/miniconda/bin/binstar", line 6, in <module>
    sys.exit(main())
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 94, in main
    description=__doc__, version=version)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 76, in binstar_main
    return args.main(args)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/binstar_client/commands/upload.py", line 204, in main
    callback=upload_print_callback(args))
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/binstar_client/__init__.py", line 435, in upload
    self._check_response(res)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/binstar_client/__init__.py", line 160, in _check_response
    raise ErrCls(msg, res.status_code)
BinstarError: (u'Invalid dist_id', 400)
```

Also, successfully pushed 2.7 packages seem to disappear after pushing 3.3 or 3.4 packages.

**Comment by jchodera** [comment]
Reported this here: https://github.com/Anaconda-Server/docs.anaconda.org/issues/84

**Comment by jchodera** [comment]
Until we hear back from continuum, I think it might be best if I convert these over to binstar CI builds so that we can at least get the Linux packages working.  Those are critical for a number of people.

**Comment by jchodera** [comment]
Jenkins is still failing to push with the same error.  I'm trying again after having manually removed the binstar packages.

**Comment by jchodera** [comment]
Difficulties are still ongoing.  Removing packages manually and rerunning Jenkins worked this time, but will need to monitor this.

**Comment by jchodera** [comment]
Reported here too:
https://github.com/Anaconda-Server/binstar/issues/173

**Comment by jchodera** [comment]
Rebuilding packages after manually deleting linux packages.

**Comment by jchodera** [comment]
I'm going to disable `openmm-dev` package building until this is resolved.

**Comment by jchodera** [comment]
`openmm-dev` package building is disabled now that there are recent `linux` and `osx` packages posted.
